### PR TITLE
Add shared libs and tests for Windows

### PR DESCRIPTION
**Pull request by shadowwalkersb**

### CODE REVIEW

**Comment by shadowwalkersb** [comment]
Need a restart on Travis.

**Comment by shadowwalkersb** [comment]
> Need a restart on Travis.

Or not. Maybe, I confused it with CircleCI. 😕

**Comment by shadowwalkersb** [comment]
CircleCI tries to upload and fails. Can we merge if there isn't anything else to do here?

**Comment by ocefpaf** [comment]
> CircleCI tries to upload and fails. Can we merge if there isn't anything else to do here?

I will take a look at that later.

**Pull request merged**
