### PR TITLE
Use recommended GSL linkage for openblas.

### PR DESCRIPTION
**Pull request by jeromekelleher**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Following up on #37, try to resolve linkage errors in #34 by using the recommended recipe for linking GSL against alternative BLAS implementations.

@duncanmmacleod: I just thought I'd try this out and see what breaks.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Cool, looks like this builds! @duncanmmacleod, would you mind trying this out on your local build to see if it fixes your linking problems?

@isuruf, what do you think, are you OK with changing the linking like this?

If we agree this is a good way to go I'll render the feedstock later before merging. Just wanted to keep the diff minimal for review purposes for the moment.

**Comment by duncanmmacleod** [comment]
@jeromekelleher, this failed to link for me, much earlier than it used to:

```
dyld: Library not loaded: @rpath/libgsl.23.dylib
  Referenced from: /Users/duncan/opt/miniconda3/conda-bld/lal_1545399317005/work/./conftest
  Reason: image not found
```

**Comment by jeromekelleher** [comment]
> @jeromekelleher, this failed to link for me, much earlier than it used to:

Ah OK, looks like there's some mac stuff going on. It was worth a try anyway. Let's see what the others think --- probably your PR is the way to go.

**Comment by jakirkham** [comment]
Looks like PR ( https://github.com/conda-forge/gsl-feedstock/pull/37 ) was merged. Is this still needed?

**Comment by jeromekelleher** [comment]
Closing this as #37 fixes our problems.

**Pull request closed without merging**
