### PR TITLE
2.3

### PR DESCRIPTION
**Pull request by dougalsutherland**
Patch is modified to only include the cmake-relevant bits from https://github.com/ampl/gsl/tree/v2.3.0. :crossed_fingers: that this patch works for this and future versions as well; it changes almost no code compared to the previous patch.

### CODE REVIEW

**Comment by dougalsutherland** [comment]
So for the record, I'm slightly worried about this huge change to the Windows patch even if it passes, because there's only existence tests on Windows – Unix runs `make check` but we don't run the cmake-defined tests on Windows. Should add that.

**Comment by jakirkham** [comment]
So the patch for CMake was added when there was no `CMakeLists.txt` before. However upstream now [has one]( https://github.com/ampl/gsl/blob/v2.3.0/CMakeLists.txt ) and does appear to do some special handling for MSVC in there. Maybe it is better to just use what they have?

**Comment by dougalsutherland** [comment]
ampl/gsl is the Windows fork that the patch is based on, not upstream. The patch I added here is just the diff between that and the upstream download.

**Comment by jakirkham** [comment]
Yep, sorry, realized my mistake and edited my comment above. Sorry for the noise.

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by dougalsutherland** [comment]
Blegh:
```
LINK: command "C:\PROGRA~2\MICROS~1.0\VC\bin\link.exe /nologo @CMakeFiles\gsl.dir\objects1.rsp /out:bin\gsl.dll /implib:gsl.lib /pdb:C:\bld\gsl_1520170835403\build_dir\bin\gsl.pdb /dll /version:0.0 /machine:X86 /INCREMENTAL:NO /DEF:C:\bld\gsl_1520170835403\work\gsl-2.3\gsl.def gslcblas.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:bin\gsl.dll.manifest" failed (exit code 1120) with the following output:
2627gsl.def : error LNK2001: unresolved external symbol gsl_multilarge_nlinear_df
2628gsl.def : error LNK2001: unresolved external symbol gsl_multilarge_nlinear_fdfvv
2629gsl.lib : fatal error LNK1120: 2 unresolved externals
```

**Comment by jakirkham** [comment]
Yep, as you have already noted elsewhere, looks like issue ( https://github.com/ampl/gsl/issues/10 ) that @jeromekelleher raised, which should have been fixed with PR ( https://github.com/ampl/gsl/pull/14 ).

**Comment by dougalsutherland** [comment]
Closing in favor of #24, unless anyone strongly feels the need for a 2.3 release.

**Pull request closed without merging**
