### PR TITLE
bump to 2.4

### LINKED ISSUE #22: update version
2.3 and 2.4 have been out for a while, but the huge patch used on Windows doesn't apply to the 2.4 sources anymore, and https://github.com/ampl/gsl/ hasn't updated it.

I might look into fixing it later, but not right now.

### PR DESCRIPTION
**Pull request by dougalsutherland**
Rather than bothering to backport the fix for the problem that's breaking #23, and now that we've realized ampl's fork accounted for the 2.4 release already, probably easier just skip the 2.3 release and release 2.4.

Fixes #22.

### CODE REVIEW

**Comment by dougalsutherland** [comment]
Linux had a test failure inside `specfunc`! Exciting. (Note that the patch is only applied on Windows, so this is on the real source distribution.) Investigating....

**Comment by dougalsutherland** [comment]
Can't get the error message from the CircleCI log, but running in the Docker image myself I got:
```
FAIL: gsl_sf_bessel_j2_e(1048576.0, &r) [168]
  expected: -3.1518539455252412e-07
  obtained: -3.1518539455252539e-07 +/- 2.7994086564622246e-22 (rel=8.88178e-16)
  fracdiff: 2.0155588470164931e-15
 tolerance: 4.5474735088646412e-13
  value/expected not consistent within reported error
  -3.151853945525253879e-07  2.799408656462224591e-22
FAIL: Bessel Functions [407]
```
This is the same problem, and the same wrong value, as [this message](https://lists.gnu.org/archive/html/help-gsl/2017-06/msg00033.html) – but that was on Windows, using an old Microsoft runtime, and the fix there was to switch to the new runtime library, which doesn't really apply here. Also similar to [this person](http://lists.libreplanet.org/archive/html/help-gsl/2008-02/msg00000.html) on OSX, though that was 2008 and they had substantially more failures than this.

Not sure what to do about this....

**Comment by jakirkham** [comment]
Maybe we need to build a newer version of `libm`? Would need to think about the implications of that. @isuruf, might have some good ideas here.

**Comment by dougalsutherland** [comment]
Yeah, I don't know if this is because `libm`'s trig functions are slightly wrong or...something else. The oldest distribution I saw anyone testing on in the "test release 2.4" thread was CentOS 7 with gcc 5, substantially newer than our image.

I guess I could try pulling the compilers from `defaults` and running on our Docker image myself to see if that would actually solve it or not.

**Comment by dougalsutherland** [comment]
@conda-forge/gsl, think this is ready to merge.

**Comment by ocefpaf** [comment]
Thanks @dougalsutherland!

**Pull request merged**
