### PR TITLE
Trigger rebuild.

### PR DESCRIPTION
**Pull request by jeromekelleher**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

Triggering rebuild and render to try and address #34

### CODE REVIEW

**Comment by jeromekelleher** [comment]
@conda-forge-admin, please rerender

**Comment by jeromekelleher** [comment]
@conda-forge/gsl this build is failing because of an [unsatisfiable dependency](https://travis-ci.org/conda-forge/gsl-feedstock/jobs/463389035#L7273) on OSX and Linux ``c_compilertoolchain_c``. Any ideas on how to resolve this? I'm lost on the details of what conda-build is doing here I'm afraid.

**Comment by ocefpaf** [comment]
I would be OK just skipping the `toolchain`. What do you think @isuruf?

**Comment by duncanmmacleod** [comment]
@conda-forge/gsl, rerunning the CI using identical changes in #36, shows that the CI passes fine now (for some reason). Can you consider merging this PR and closing #36?

cc @jeromekelleher

**Comment by jeromekelleher** [comment]
Thanks @duncanmmacleod! I've pushed an update to force a rebuild, which will hopefully pass also.

Out of interest, what has changed to make you think this would work?

**Comment by duncanmmacleod** [comment]
@jeromekelleher, I think last week I was able to reproduce your failures, but today the local builds passed (macOS local, and linux under docker), which suggested some sort of transient problems. I have no idea what actually might have changed in the mean time. Fingers crossed.

**Comment by jeromekelleher** [comment]
It works; hooray! @conda-forge/gsl can someone push the merge button here please?

**Pull request merged**
